/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class MicroRaiden {
    public static void main(String[] args) {
        System.out.println("Hello MicroRaiden Java");
    }
}
