/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class MicroRaidenTest {
    @Test public void test() {
        MicroRaiden classUnderTest = new MicroRaiden();
        assert(true);
    }
}
